python:
  global:
    modules:
      standard:
        - import: pandas
          install: pandas
      test:
        - import: pytest
          install: pytest

      api-connection:
        - import: requests
          install: requests
        - import: flask
          install: Flask

  services:
    # Modules needed for this service
    modules:
      - import: boto3
        install: boto3
    aws:
      profiles:
        # Default snowflake context
        default:
          primary_key:
          secret_primary_key:
          region: